---
- name: Get the project id for project named {{ project_template['name'] }}
  import_tasks: gns3-getprojectid.yml
  tags: import_gns3_getprojectid

- name: Get a list of nodes already created in project named {{ project_template['name'] }}
  import_tasks: gns3-getnodes.yml
  tags: import_gns3_getnodes

- name: Delete nodes in project
  uri:
    url: "http://{{ ip }}:{{ port }}/v2/projects/{{ project_id }}/nodes/{{ nodeitem }}"
    method: DELETE
    body_format: json
    status_code: [204, 400, 404, 409]
    headers:
      Content-Type: application/json
    force_basic_auth: yes
    url_username: "{{ project_template['username'] }}"
    url_password: "{{ project_template['password'] }}"
  register: result_gns3_nodes_delete
  with_items: "{{ result_gns3_nodes_get | json_query('json[].node_id') | list }}"
  loop_control:
    loop_var: nodeitem
  delegate_to: localhost
  run_once: true
  ignore_errors: true
  tags: result_gns3_nodes_delete
...