---
- name: Get the nodes in project named {{ project_template['name'] }}
  block:
    - name: Get the nodes in project named {{ project_template['name'] }}
      uri:
        url: "http://{{ ip }}:{{ port }}/v2/projects/{{ project_id }}/nodes"
        method: GET
        body_format: json
        status_code: [200]
        headers:
          Content-Type: application/json
        force_basic_auth: yes
        url_username: "{{ username }}"
        url_password: "{{ password }}"
      register: result_gns3_nodes_get

  ignore_errors: true
  delegate_to: localhost
  run_once: true
  when:
    - project_id is defined
    - project_id != ''
  tags: gns3_nodes_get
...